# This workflow installs the package and builds the docs
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build the docs

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      #------------------------------
      #  install & configure poetry
      #------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install poetry dynamic versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      #-------------------------------------------
      #  install root project and build the docs
      #-------------------------------------------
      - name: Install library
        run: poetry install --no-interaction --with docs

      - name: Build the docs
        run: poetry run make --directory=docs html
