# This workflow installs the package and runs the tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: nightly

on:
  schedule:
    # see https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
    # 05:00 UTC = 06:00 CET = 07:00 CEST
    - cron: "0 5 * * TUE"
jobs:
  pytest:

    strategy:
      matrix:
        # keep consistent with py-version badge in README.md and docs/index.rst
        python-version: ['3.11']
      fail-fast: false

    runs-on: ubuntu-latest
    name: py${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the package
      run: pip install --editable .[tests]

    - name: Test with pytest
      run: pytest tests
